### ISSUE TITLE
Why are these errors reported? FileNotFoundError: [Errno 2] No such file or directory: 'e2rm': 'e2rm'

### ISSUE THREAD

**Issue by Uniqu3Ch1** [nongiach/arm_now#3]
Hellow @nongiach
I encountered some errors when I created the virtual machine using arm_now. Can you help me to fix this error? "FileNotFoundError: [Errno 2] No such file or directory: 'e2rm': 'e2rm'"
And here are traceback log ：
Traceback (most recent call last):
  File "/usr/local/bin/arm_now", line 11, in <module>
    load_entry_point('arm-now==1.1', 'console_scripts', 'arm_now')()
  File "/usr/local/lib/python3.6/dist-packages/arm_now-1.1-py3.6.egg/arm_now/arm_now.py", line 399, in main
  File "/usr/local/lib/python3.6/dist-packages/sigtools/modifiers.py", line 158, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/clize/runner.py", line 360, in run
    ret = cli(*args)
  File "/usr/local/lib/python3.6/dist-packages/clize/runner.py", line 220, in __call__
    return func(*posargs, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/clize/runner.py", line 262, in _cli
    return func('{0} {1}'.format(name, command), *args)
  File "/usr/local/lib/python3.6/dist-packages/clize/runner.py", line 220, in __call__
    return func(*posargs, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/arm_now-1.1-py3.6.egg/arm_now/arm_now.py", line 354, in start
  File "/usr/local/lib/python3.6/dist-packages/arm_now-1.1-py3.6.egg/arm_now/arm_now.py", line 239, in config_filesystem
  File "/usr/local/lib/python3.6/dist-packages/arm_now-1.1-py3.6.egg/arm_now/arm_now.py", line 231, in ext2_rm
  File "/usr/lib/python3.6/subprocess.py", line 286, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'e2rm': 'e2rm'

I'm sure I installed all the dependencies, but I still can't create the arm virtual machine.
Can you help me?  
Thank you 
Please

**Comment by nongiach** [comment]
Hey, can you please follow these steps one by one?
thanks
```sh
$ mkdir test
$ cd test
$ arm_now start armv5-eabi --clean
Welcome to Buildroot
buildroot login: root
# uname -m
armv7l
```

**Comment by Ektoplasma** [comment]
@Uniqu3Ch1 If you still have some issues, you should install e2tools.
