### ISSUE TITLE
can not run arm_now

### ISSUE THREAD

**Issue by kofteror** [nongiach/arm_now#40]
Hey.. trying to run arm_now on VM machine ubuntu20 with no luck

ubuntu:~$ arm_now
Traceback (most recent call last):
  File "/home/thomas/.local/lib/python3.8/site-packages/arm_now/utils.py", line 44, in which
    subprocess.check_output(["which", filename])
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['which', 'e2cp']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/arm_now", line 11, in <module>
    load_entry_point('arm-now==1.24', 'console_scripts', 'arm_now')()
  File "/home/thomas/.local/lib/python3.8/site-packages/arm_now/arm_now.py", line 72, in main
    check_dependencies_or_exit()
  File "/home/thomas/.local/lib/python3.8/site-packages/arm_now/arm_now.py", line 233, in check_dependencies_or_exit
    which("e2cp",
  File "/home/thomas/.local/lib/python3.8/site-packages/arm_now/utils.py", line 47, in which
    if distribution() in kwargs:
  File "/home/thomas/.local/lib/python3.8/site-packages/arm_now/utils.py", line 39, in distribution
    return platform.linux_distribution()[0].lower()
AttributeError: module 'platform' has no attribute 'linux_distribution'

Help will be very appreciated

**Comment by SakiiR** [comment]
Did you install the `e2tools` package ?

**Comment by nongiach** [comment]
Closing this it was fixed by realgam3.

Have a good day.
